import {useConfig} from '#src/Context/Contexts/ConfigContext';
import {STALE} from '#src/Libraries/Time/Time';
import {usePublicQuery} from '#src/Queries/OpenQuery';
import {ShipIndex} from '#src/Structs/ShipStructs';

/**
 * The deck-map index (deck names, stateroom ranges, and every venue/cabin/facility
 * box) generated by the map-extractor tool and served alongside the deck images
 * it indexes, under /public/ship/<code>/ — one ship's assets per code, so
 * switching ships (appConfig.shipCode) is a different endpoint and therefore a
 * different query cache entry, rather than a stale one colliding with a new
 * one at the same URL. Long staleTime: this only changes when the server
 * operator deploys a new ship's assets, and the persisted query cache keeps
 * it available offline.
 */
export const useShipIndexQuery = (options = {}) => {
  const {appConfig} = useConfig();
  return usePublicQuery<ShipIndex>(`/public/ship/${appConfig.shipCode}/ship.json`, {
    staleTime: STALE.HOURS.TWENTY_FOUR,
    ...options,
  });
};
