import {STALE} from '#src/Libraries/Time/Time';
import {usePublicQuery} from '#src/Queries/OpenQuery';
import {ShipIndex} from '#src/Structs/ShipStructs';

/**
 * The deck-map index (deck names, stateroom ranges, and every venue/cabin/facility
 * box) generated by the map-extractor tool and served alongside the deck images
 * it indexes. Long staleTime: this only changes when the server operator deploys
 * a new ship's assets, and the persisted query cache keeps it available offline.
 */
export const useShipIndexQuery = (options = {}) => {
  return usePublicQuery<ShipIndex>('/public/ship/ship.json', {
    staleTime: STALE.HOURS.TWENTY_FOUR,
    ...options,
  });
};
