import {useLinkTo} from '@react-navigation/native';
import {useCallback, useEffect} from 'react';
import {Linking} from 'react-native';
import notifee, {Event, EventType, Notification} from 'react-native-notify-kit';

import {useSwiftarrQueryClient} from '#src/Context/Contexts/SwiftarrQueryClientContext';
import {PressAction} from '#src/Enums/Notifications';
import {useFezCacheReducer} from '#src/Hooks/Fez/useFezCacheReducer';
import {createLogger} from '#src/Libraries/Logger';
import {getUrlForNotificationEvent} from '#src/Libraries/Notifications/SocketNotification';
import {appUrl} from '#src/Libraries/UrlParser';
import {useUserNotificationDataQuery} from '#src/Queries/Alert/NotificationQueries';
import {NotificationTypeData} from '#src/Structs/SocketStructs';

const logger = createLogger('AppEventHandler.tsx');

/**
 * High level functional component to handle app events that are generated by reactions to notifications.
 * Usually used when the user taps on a notification or hits one of its action buttons.
 */
export const AppEventHandler = () => {
  const linkTo = useLinkTo();
  const {refetch: refetchUserNotificationData} = useUserNotificationDataQuery({enabled: false});
  const {apiGet} = useSwiftarrQueryClient();
  const {invalidateFez} = useFezCacheReducer();

  // Responds to a "Mark As Read" notification action press. Marks the content read on the
  // server, then syncs whatever local cache backs that content's unread state so badges
  // update immediately instead of waiting for the next unrelated refetch (or app relaunch).
  const handleMarkAsRead = useCallback(
    async (notification?: Notification) => {
      if (notification?.id) {
        await notifee.cancelDisplayedNotification(notification.id);
      }
      if (notification?.data) {
        await apiGet(notification.data.markAsReadUrl.toString());
        switch (notification.data.type) {
          case NotificationTypeData.seamailUnreadMsg:
          case NotificationTypeData.fezUnreadMsg:
          case NotificationTypeData.privateEventUnreadMsg:
            await invalidateFez(notification.data.contentID?.toString());
            break;
          default:
            break;
        }
        await refetchUserNotificationData();
      }
    },
    [apiGet, invalidateFez, refetchUserNotificationData],
  );

  // Foreground events occur when the app is front and center in the users view.
  // This has to be a useEffect otherwise the navigator could be used before it's
  // initialized. Which still functions but throws an error.
  useEffect(() => {
    const handleForegroundEvent = async (event: Event) => {
      logger.debug('handleForegroundEvent responding to event', event.type);

      // When I made notification permissions optional, I started seeing EventType.DELIVERED events make
      // it in here. This caused the app to launch whenever a notification was received which is unacceptable.
      // Limiting the actions that can trigger the app made it better.
      if (event.type === EventType.DELIVERED || event.type === EventType.DISMISSED) {
        logger.debug('onBackgroundEvent skipping delivered or dismissed event');
        return;
      }

      const {notification, pressAction} = event.detail;

      // Look for Mark As Read press actions. This will fire off a request to the server which
      // assumes the user read the content and updates its state accordingly. Refresh the UND
      // so that we can pick up the appropriate state.
      if (pressAction?.id === PressAction.markAsRead) {
        logger.info('handleForegroundEvent is marking as read.');
        await handleMarkAsRead(notification);
        return;
      }

      // The default response is to then navigate the user somewhere.
      const url = getUrlForNotificationEvent(event.type, notification, pressAction);
      if (url) {
        logger.debug('handleForegroundEvent responding to url', url);
        // NavigationContainer's onStateChange will close menus when linkTo() triggers navigation
        linkTo(url);
      } else {
        logger.warn('handleForegroundEvent unable to determine URL.');
      }
    };

    // We get the unsubscribe function returned from registering the handler.
    const unsubscribe = notifee.onForegroundEvent(handleForegroundEvent);

    return () => {
      unsubscribe();
    };
  }, [handleMarkAsRead, linkTo]);

  // Background events occur when the app is still running but not in the users view.
  // The OS may kill the app at any time.
  notifee.onBackgroundEvent(async (event: Event) => {
    logger.debug('onBackgroundEvent responding to event', event.type);

    // When I made notification permissions optional, I started seeing EventType.DELIVERED events make
    // it in here. This caused the app to launch whenever a notification was received which is unacceptable.
    // Limiting the actions that can trigger the app made it better.
    if (event.type === EventType.DELIVERED || event.type === EventType.DISMISSED) {
      logger.debug('onBackgroundEvent skipping delivered or dismissed event');
      return;
    }

    const {notification, pressAction} = event.detail;

    // Look for Mark As Read press actions. This will fire off a request to the server which
    // assumes the user read the content and updates its state accordingly. Refresh the UND
    // so that we can pick up the appropriate state.
    if (pressAction?.id === PressAction.markAsRead) {
      logger.info('handleForegroundEvent is marking as read.');
      await handleMarkAsRead(notification);
      return;
    }

    // The default response is to then navigate the user somewhere.
    const url = getUrlForNotificationEvent(event.type, notification, pressAction);
    if (url) {
      const linkingUrl = appUrl(url);
      logger.debug('onBackgroundEvent launching url', linkingUrl);
      await Linking.openURL(linkingUrl);
    } else {
      logger.warn('onBackgroundEvent event was not a respondable action. Skipping...');
      await Linking.openURL(appUrl('home'));
    }
  });

  // Void is not a valid React component.
  return null;
};
