import {Linking} from 'react-native';
import notifee from '@notifee/react-native';
import {useLinkTo} from '@react-navigation/native';
import {getUrlForEvent} from '../../libraries/Events';

/**
 * High level functional component to handle events that are generated by reactions to notifications.
 * Usually used when the user taps on a notification or hits one of its action buttons.
 */
export const EventHandler = () => {
  const linkTo = useLinkTo();

  // Foreground events occur when the app is front and center in the users view.
  notifee.onForegroundEvent(async ({type, detail}) => {
    const {notification, pressAction} = detail;
    const url = getUrlForEvent(type, notification, pressAction);

    if (url) {
      linkTo(url);
    }
  });

  // Background events occur when the app is still running but not in the users view.
  // The OS may kill the app at any time.
  notifee.onBackgroundEvent(async ({type, detail}) => {
    const {notification, pressAction} = detail;
    const url = getUrlForEvent(type, notification, pressAction) || 'tricordarr://hometab';

    await Linking.openURL(`tricordarr:/${url}`); // url starts with a /, so only add one.
  });

  // Void is not a valid React component.
  return null;
};
