/**
 * Deck-map metadata generated by the map-extractor tool
 * (https://github.com/jocosocial/map-extractor) and served by Swiftarr at
 * /public/ship/ship.json, alongside the deck1.png ... deckN.png images it
 * indexes. Every image and every coordinate below comes from the same
 * shared crop box, so a normalized box addresses the image at any size.
 */

export type ShipLabelKind = 'venue' | 'cabin' | 'facility';
export type ShipLabelSide = 'port' | 'starboard' | 'center';
export type ShipRegion = 'forward' | 'midship' | 'aft';

export interface ShipLabel {
  kind: ShipLabelKind;
  /// Machine key for a venue/facility, derived from its printed caption. Null for cabins.
  slug: string | null;
  /// Display name. For cabins, "Stateroom <number><suffix>".
  name: string;
  /// The caption as printed, newline-joined if it was stacked across lines.
  raw: string;
  /// Stateroom number. Cabins only.
  number: number | null;
  /// Stateroom category prefix (e.g. "F", "VQ"). Cabins only.
  category: string | null;
  /// Stateroom unit suffix letter for lettered sub-units (e.g. "D7000D"). Cabins only.
  suffix: string | null;
  /// Normalized box, fractions of the deck image: 0-1 from the top-left.
  x: number;
  y: number;
  w: number;
  h: number;
  /// Derived from the label's position relative to the deck's hull, not from anything printed.
  side: ShipLabelSide;
  region: ShipRegion;
  /// Hand-maintained additional names to match on. Venues/facilities only.
  aliases: string[];
  /// Hand-maintained Sched-style location strings ("World Stage, Deck 2, Forward") that resolve to this label.
  matches: string[];
}

export interface ShipDeckRegions {
  forward: [number, number];
  midship: [number, number];
  aft: [number, number];
}

export interface ShipDeck {
  number: number;
  /// Deck name as printed ("Main"), or null if the title block wasn't recognized.
  name: string | null;
  /// "<name> Deck", or null.
  title: string | null;
  roomStart: number | null;
  roomEnd: number | null;
  /// Filename under /public/ship/, e.g. "deck1.png".
  image: string;
  /// This deck's own ink bounds within the shared crop, normalized. Shorter decks do not fill the crop.
  hull: {x: number; y: number; w: number; h: number};
  /// Forward/midship/aft thirds of this deck's hull, as normalized y-ranges.
  regions: ShipDeckRegions;
  labels: ShipLabel[];
}

export interface ShipIndex {
  schemaVersion: number;
  /// Ship code from the source filename ("ed").
  ship: string;
  shipName: string | null;
  source: string;
  sourceSha256: string;
  generated: string;
  geometry: {
    cropPt: {w: number; h: number};
    imagePx: {w: number; h: number} | null;
    zoom: number;
    /// Orientation invariant every side/region in this file assumes.
    orientation: {forward: 'top'; port: 'left'};
  };
  decks: ShipDeck[];
}
