export enum AppIcons {
  // Chat
  seamailCreate = 'email-plus',
  seamail = 'email',
  krakentalkCreate = 'phone-outgoing',
  krakentalk = 'phone',
  chat = 'chat',
  details = 'account-details',
  // Profile
  privateNoteEdit = 'note-edit',
  // Generic
  new = 'plus',
  insert = 'plus-circle-outline',
  newImage = 'image-plus',
  delete = 'delete-forever',
  submit = 'send-circle-outline',
  scrollDown = 'arrow-down-circle',
  back = 'arrow-left',
  reload = 'reload',
  error = 'alert-circle-outline',
  menu = 'dots-vertical',
  favorite = 'star',
  unfavorite = 'star-off',
  block = 'cancel',
  unblock = 'check-circle',
  mute = 'volume-off',
  unmute = 'volume-high',
  report = 'alert-octagon',
  help = 'help-circle',
  copy = 'content-copy',
  // Users
  user = 'account',
  edituser = 'account-edit',
  group = 'account-group',
  password = 'form-textbox-password',
  moderator = 'security',
  twitarteam = 'check-decagram',
  tho = 'shield-crown',
  home = 'home',
  notification = 'bell-badge',
  forum = 'forum',
  events = 'calendar',
  settings = 'cog',
  webview = 'web',
}
