export enum NotificationType {
  // announcement = 'announcement',
  // seamailUnreadMsg = 'seamailUnreadMsg',
  // fezUnreadMsg = 'fezUnreadMsg',
  // alertwordTwarrt = 'alertwordTwarrt',
  // alertwordPost = 'alertwordPost',
  // twarrtMention = 'twarrtMention',
  // forumMention = 'forumMention',
  // nextFollowedEventTime = 'nextFollowedEventTime',
  announcement,
  seamailUnreadMsg,
  fezUnreadMsg,
  alertwordTwarrt,
  alertwordPost,
  twarrtMention,
  forumMention,
  nextFollowedEventTime,
}
